ROCm/rocSPARSE

.clang-format, clients/include/testing_axpyi.hpp, clients/include/testing_coo2csr.hpp, clients/include/testing_coomv.hpp, clients/include/testing_coosort.hpp, clients/include/testing_csr2coo.hpp, clients/include/testing_csr2csc.hpp, clients/include/testing_csr2ell.hpp, clients/include/testing_csr2hyb.hpp, clients/include/testing_csrilu0.hpp, clients/include/testing_csrilusv.hpp, clients/include/testing_csrmm.hpp, clients/include/testing_csrmv.hpp, clients/include/testing_csrsort.hpp, clients/include/testing_csrsv.hpp, clients/include/testing_doti.hpp, clients/include/testing_ell2csr.hpp, clients/include/testing_ellmv.hpp, clients/include/testing_gthr.hpp, clients/include/testing_gthrz.hpp, clients/include/testing_hybmv.hpp, clients/include/testing_identity.hpp, clients/include/testing_roti.hpp, clients/include/testing_sctr.hpp, library/src/handle.cpp, library/src/include/logging.h, library/src/level2/coomv_device.h, library/src/level3/csrmm_device.h
- Additional options are now available in clang-format, and they need to be applied to Jenkins after I upgraded CI from rocm2.4 to rocm2.5
=> New clang-format file applied for rocm2.5

Jenkinsfile, docker/dockerfile-build-centos, docker/dockerfile-build-ubuntu-rock
This PR adds CI testing for our new hip-clang compiler. For a period of time, we'll have to support both the hcc and the hip-clang compilers, thus we'll have to test both in CI.
=> Added hip-clang support

Jenkinsfile
changes http://hsautil.amd.com/job/ROCmSoftwarePlatform/job/rocsparse to correct link- http://hsautil.amd.com/job/ROCmSoftwarePlatform/job/rocSPARSE upon CI failures
=> fixed email notification link

clients/tests/test_csrilusv.cpp
=> disabling bmwcra matrix for csr ilu solve test

Jenkinsfile
Too many executors are launched at 22; this will help distribute Jenkins jobs better on the server.
=> Staggering Jenkins build times to avoid overloading server

library/src/precond/csrilu0_device.h
Fixes a bug where zero pivots were wrong when using ``rocsparse_index_base_one``
=> [csrilu0] pivot fix

CMakeLists.txt, library/src/extra/rocsparse_csrgemm.cpp
quick return was missing when ``alpha == null`` and ``beta != null``
=> csrgemm fix

install.sh
Fix for missing yaml packages when building clients.
We need this picked for hip-clang 2.10 branch.
=> install.sh script updated (#185)

CMakeLists.txt, clients/CMakeLists.txt, cmake/Dependencies.cmake, cmake/Packaging.cmake, install.sh, library/CMakeLists.txt
- ROCm stack install path needs to be provided using the
variable ROCM_PATH as a cmake parameter. If it is not
provided, ROCm stack components are searched in /opt/rocm
- Package is generated to install into ROCM_PATH by setting
it to CMAKE_PACKAGING_INSTALL_PREFIX, if defined in the env
otherwise default into /opt/rocm
- RUNPATH is set in the lib only if ROCM_RPATH env is defined
with the rpath
Signed-off-by: Pruthvi Madugundu <mpruthvi@gmail.com>
=> rocSPARSE changes to support multiple ROCM installation

CMakeLists.txt, clients/CMakeLists.txt, cmake/Dependencies.cmake, cmake/Packaging.cmake, install.sh, library/CMakeLists.txt
- New mode of building is added "-r,--relocatable" which is used
for ROCm stack installed in /opt/rocm-ver.
- Below CMAKE parameters are set/overwritten in above mode
CMAKE_INSTALL_PREFIX
CPACK_PACKAGING_INSTALL_PREFIX
CMAKE_PREFIX_PATH
CMAKE_SHARED_LINKER_FLAGS
ROCM_DISABLE_LDCONFIG
ROCM_PATH
Signed-off-by: Pruthvi Madugundu <mpruthvi@gmail.com>
=> rocSPARSE Separate build flag to support multiple ROCM installation

library/src/rocsparse_module.f90
The usage of `x` for hex numbers is a `gfortran` extension, not supported by newer versions like `gfortran 10.2`.
Furthermore, the usage of boz literals in enums is not supported by the fortran standard, neither in `f90` nor in `f18`.
=> Remove boz literals

CMakeLists.txt, clients/include/testing_prune_csr2csr_by_percentage.hpp, clients/tests/test_csrsm.yaml, library/CMakeLists.txt, library/include/rocsparse-functions.h, library/src/level2/rocsparse_csrsv.hpp, library/src/level3/rocsparse_csrsm.hpp, library/src/precond/bsrilu0_device.h, library/src/precond/rocsparse_bsrilu0.hpp, library/src/precond/rocsparse_csric0.hpp, library/src/precond/rocsparse_csrilu0.hpp
- Replace old version of xnack compiler off flag with the new syntax for the flag
=> Replace old xnack off compiler flag with new version

CMakeLists.txt
AMDGPU_TARGETS marked as cache string.
When after include Dependencies.cmake, AMDGPU_TARGETS always get cached variable gfx900;gfx906;gfx908, Its means never used AMDGPU_TARGETS.
This caused ROCm3.9 crashed on gfx803. https://github.com/RadeonOpenCompute/ROCm/issues/1269
resolves https://github.com/RadeonOpenCompute/ROCm/issues/1269
- Dont let AMDGPU_TARGETS always be overwriten.
=> move AMDGPU_TARGETS before include Dependencies

.jenkins/staticanalysis.groovy, docs/Doxyfile, docs/run_doc.sh, docs/run_doxygen.sh, docs/source/conf.py
I've updated the Jenkins config to host the Sphinx docs for each PR. I also ported over some of the doc script improvements I made on rocBLAS and rocSOLVER.
- Switch documentation link on Jenkins from Doxygen to Sphinx output
- Configure Doxygen to process headers in-place
- Allow doc scripts to run from anywhere
=> Fix Jenkins docs link and minor cleanup

CMakeLists.txt
The vendor string "AMD" is being added to ROCm clang compiler.  This updates the compiler version check in cmake.
=> Support new clang string for ROCmCC

CMakeLists.txt, clients/CMakeLists.txt
Check the CMAKE_CXX_COMPILER_ID string instead of parsing the
Clang version string.
=> Detect Clang using the compiler ID

library/CMakeLists.txt
resolves #___
- Build interface updated to internal build warnings.
-
-
=> Fix Reorg include warnings

cmake/Dependencies.cmake, toolchain-linux.cmake
resolves #___
- Update HIP bin prefix path to rocm_path (rocm_path/bin will be used for hipcc as per the reorg structure)
-
-
=> Updated HIP Bin prefix Path to rocm_path

library/src/include/utility.h
- When pointer_mode is device, `LOG_TRACE_SCALAR_VALUE` and `LOG_BENCH_SCALAR_VALUE` copy values and sync even if results will not be printed. Som rocSPARSE functions have up to 4 transfers+syncs (alpha and beta for log_trace and log_bench).
=> Do not copy scalar values from device and sync if logging is disabled

scripts/performance/matrices/CMakeLists.txt, scripts/performance/matrices/README, scripts/performance/matrices/build_convert.sh
resolves SWDEV-374810 and SWDEV-375165 
- Adding a shell and CMake scripts to build the required executable to convert matrix files
=> adding a script to build the executable convert. (#478)

library/src/include/utility.h, library/src/level2/rocsparse_bsrsv_solve.cpp, library/src/level2/rocsparse_csritsv_solve.cpp, library/src/level2/rocsparse_csrsv_analysis.cpp, library/src/level2/rocsparse_csrsv_solve.cpp, library/src/level3/rocsparse_csrsm.cpp
Instead of `hipMemcpyAsync` use a simple kernel to set values in device memory.
`hipMemcpyAsync` blocks the host until the operations in the stream complete if the source is not pinned memory.
Using a kernel, the host doesn't have to wait. Note that an atomic write from the host wouldn't work as the copy has to happen after the current operations in the stream complete.
This matters in latency bound scenarios, for example compare the following traces from using rocsparse in petsc:
**Before this change:**
On the track named Hip activity, its visible that the host is blocked waiting for the copy to complete.
**After:**
There are more similar copies in rocSPARSE, but in this PR I only propose this for the pivot copies, as a first step.
=> Use a kernel for small copies to device

library/include/rocsparse-types.h
This fixes a wrong comment from `rocsparse_set_storage_mode` to `rocsparse_set_mat_storage_mode`
=> Fix comment

clients/testings/testing_bsrmv.cpp
- This was fixed in https://github.com/ROCmSoftwarePlatform/rocSPARSE/commit/db2c9219874be7c04b1a7023d5153d733bd001ca but I don't want to cherry pick this entire PR into 5.7
=> Fix failing bsrmv stress test

CHANGELOG.md, clients/testings/testing_gpsv_interleaved_batch.cpp, library/src/precond/rocsparse_gpsv_interleaved_batch.cpp
The minimum size $m$ is not valid in the code according to the documentation.
Therefore the [GPSV example](https://github.com/ROCmSoftwarePlatform/rocSPARSE/blob/develop/clients/samples/example_gpsv.cpp) in this repo does not work.
- fix to $m\ge3$ in the code
- fix to $m\ge3$ in the test description
- update CHANGELOG
=> Fix gpsv minimum m size

library/src/level3/rocsparse_csrsm_solve.cpp, library/src/precond/rocsparse_bsric0.cpp, library/src/precond/rocsparse_bsrilu0.cpp, library/src/precond/rocsparse_csric0.cpp, library/src/precond/rocsparse_csrilu0.cpp
* the use of gcnarch has been somehow reverted from the many commits related to argument checkings
resolves #SWDEV-415164
=> SWDEV-415164 (#656)

library/src/rocsparse_argdescr.cpp, library/src/rocsparse_message.cpp
resolves #SWDEV-429034
removes unnecessary inclusions of unistd.h and sys/types.h
=> removes unnecessary inclusions of unistd.h and sys/types.h (#661)
