- library/src/handle.cpp
- library/src/level1/doti_device.h
- library/src/level1/rocsparse_doti.hpp
> changed doti to be non-blocking when device pointer mode is used

- library/CMakeLists.txt
> changing link libraries to hip::device

- install.sh
> add missing library dependency on rpm-build for CentOS

- cmake/Dependencies.cmake
> fix hip packaging directory for hip runtime

- Jenkinsfile
- clients/common/rocsparse_template_specialization.cpp
- clients/common/utility.cpp
- clients/include/testing_csrmv.hpp
- clients/samples/example_csrmv.cpp
- docker/dockerfile-build-ubuntu
- library/include/rocsparse-functions.h
- library/src/conversion/csr2ell_device.h
- library/src/conversion/ell2csr_device.h
- library/src/conversion/rocsparse_ell2csr.cpp
- library/src/level2/rocsparse_csrmv.cpp
- library/src/rocsparse_auxiliary.cpp
> updated jenkins to test with rocm2.0

- library/src/level2/coomv_device.h
- library/src/level2/csrsv_device.h
- library/src/level2/ellmv_device.h
> cache usage optimizations

- scripts/performance/dcsrmv.sh
- scripts/performance/scsrmv.sh
> mod. perf. scripts to run all matrices in directory

- docs/source/library.rst
> fix in documentation

- clients/include/testing_csrsv.hpp
- library/src/include/common.h
- library/src/level2/csrmv_device.h
- library/src/level2/csrsv_device.h
* changing from ds_swizzle to dpp reductions
* changing to hip atomics
> performance improvement through dpp reductions

- library/CMakeLists.txt
- scripts/performance/dcsrsv.sh
- scripts/performance/scsrsv.sh
* faster linking with -fno-gpu-rdz
* csrsv performance scripts
> faster linking and csrsv perf. scripts

- library/CMakeLists.txt
> -fno-gpu-rdc requires compile-time --amdgpu-target= options

- library/CMakeLists.txt
> added amdgpu-targets to linker step

- clients/samples/example_handle.cpp
- library/include/rocsparse-version.h.in
- library/src/rocsparse_auxiliary.cpp
> versioning fix

- CMakeLists.txt
> bump version

- CMakeLists.txt
- cmake/Dependencies.cmake
> removed hip dependency on specific version

- Jenkinsfile
> build clients in CI

- library/src/level2/rocsparse_csrsv.hpp
> returning NYI status in csrsv if called with transposed matrix

- clients/tests/rocsparse_gtest_main.cpp
> reduced CI test output

- CMakeLists.txt
- clients/benchmarks/client.cpp
- clients/common/rocsparse_template_specialization.cpp
- clients/include/rocsparse.hpp
- clients/include/rocsparse_host.hpp
- clients/include/rocsparse_template.yaml
- clients/include/testing_dotci.hpp
- clients/tests/CMakeLists.txt
- clients/tests/test_dotci.cpp
- clients/tests/test_dotci.yaml
- clients/tests/test_doti.cpp
- clients/tests/test_doti.yaml
- library/include/rocsparse-complex-types.h
- library/include/rocsparse-functions.h
- library/src/level1/dotci_device.h
- library/src/level1/doti_device.h
- library/src/level1/rocsparse_dotci.cpp
- library/src/level1/rocsparse_dotci.hpp
- library/src/level1/rocsparse_doti.cpp
Adding complex support for
- doti
- dotci
> added complex level1 support #2

- CMakeLists.txt
- clients/benchmarks/client.cpp
- clients/common/rocsparse_template_specialization.cpp
- clients/include/rocsparse.hpp
- clients/include/rocsparse_host.hpp
- clients/include/rocsparse_template.yaml
- clients/include/testing_csr2hyb.hpp
- clients/include/testing_hybmv.hpp
- clients/include/utility.hpp
- clients/tests/test_csr2hyb.cpp
- clients/tests/test_csr2hyb.yaml
- clients/tests/test_hybmv.cpp
- clients/tests/test_hybmv.yaml
- docs/source/library.rst
- library/include/rocsparse-functions.h
- library/src/conversion/rocsparse_csr2hyb.cpp
- library/src/handle.cpp
- library/src/include/handle.h
- library/src/include/utility.h
- library/src/level2/rocsparse_hybmv.cpp
> added complex level2 hybmv and csr2hyb support

- clients/common/rocsparse_template_specialization.cpp
> fixed missing bracket (got lost after merge)

- CMakeLists.txt
- clients/benchmarks/client.cpp
- clients/common/rocsparse_template_specialization.cpp
- clients/include/rocsparse.hpp
- clients/include/rocsparse_template.yaml
- clients/include/testing_csrilu0.hpp
- clients/tests/test_csrilu0.cpp
- clients/tests/test_csrilu0.yaml
- docs/source/library.rst
- library/include/rocsparse-complex-types.h
- library/include/rocsparse-functions.h
- library/src/precond/rocsparse_csrilu0.cpp
> added complex precond csrilu0 support

- clients/tests/test_csrmm.yaml
> csrmm unit test update

- Jenkinsfile
- clients/include/rocsparse_common.yaml
- clients/tests/test_axpyi.yaml
- clients/tests/test_coo2csr.yaml
- clients/tests/test_coomv.yaml
- clients/tests/test_coosort.yaml
- clients/tests/test_cscsort.yaml
- clients/tests/test_csr2coo.yaml
- clients/tests/test_csr2csc.yaml
- clients/tests/test_csr2ell.yaml
- clients/tests/test_csr2hyb.yaml
- clients/tests/test_csrgemm.yaml
- clients/tests/test_csrilu0.yaml
- clients/tests/test_csrilusv.cpp
- clients/tests/test_csrilusv.yaml
- clients/tests/test_csrmm.yaml
- clients/tests/test_csrmv.yaml
- clients/tests/test_csrsort.yaml
- clients/tests/test_csrsv.yaml
- clients/tests/test_dotci.yaml
- clients/tests/test_doti.yaml
- clients/tests/test_ell2csr.yaml
- clients/tests/test_ellmv.yaml
- clients/tests/test_gthr.yaml
- clients/tests/test_gthrz.yaml
- clients/tests/test_hybmv.yaml
- clients/tests/test_identity.yaml
- clients/tests/test_roti.yaml
- clients/tests/test_sctr.yaml
> major unit test (test cases) update

- clients/include/flops.hpp
> spmv gflops corrected

- install.sh
Fix for missing yaml packages when building clients.
> install.sh script updated

- CMakeLists.txt
- library/include/rocsparse-complex-types.h
complex division workaround for CentOS in triangular solve
> CentOS fix for complex triangular solve

- clients/tests/test_csrsv.yaml
> csrsv unit test update

- library/include/rocsparse-types.h
> added rocsparse_direction enum

- CMakeLists.txt
- library/src/level2/coomv_device.h
Fixed an issue with coomv where shared memory reads could run out of bounds.
> fixed an issue with coomv

- library/src/level2/csrmv_device.h
- library/src/level2/rocsparse_csrmv.cpp
- Fixed bug in csrmv adaptive algorithm
> hotfix for csrmv bug

- library/CMakeLists.txt
resolves #___
- Dep include files copy to build dir
-
-
> Dep Include headers copy to build dir

- clients/samples/CMakeLists.txt
- clients/tests/CMakeLists.txt
- library/CMakeLists.txt
- library/include/rocsparse-auxiliary.h
- library/include/rocsparse-functions.h
- library/include/rocsparse-types.h
- library/include/rocsparse.h
- library/src/include/common.h
- library/src/include/handle.h
- library/src/include/status.h
- library/src/include/templates.h
resolves #___
- Include Path Reorg Dep Changes
-
-
> Dep Changes for Include Path Reorg

- library/CMakeLists.txt
resolves #___
- Include Path Reorg, Dep Changes after file copy to build dir
-
-
> Include Path Reorg - Fix

- clients/tests/CMakeLists.txt
- deps/external-gtest.cmake
> Updating to Googletest 1.11.0

- CHANGELOG.md
- CMakeLists.txt
- library/CMakeLists.txt
> Update changelog for 5.1

- CMakeLists.txt
- library/CMakeLists.txt
resolves #___
- Changes for GNU install dir enhancements
-
-
> GNUInstall Dir enhancements

- CMakeLists.txt
- Cherry picks in Navi support
> Add build support for Navi31 and 33 (#401)

- CHANGELOG.md
- Cherry pick in update to changelog for rocm 5.4
> Update changlog for rocm 5.4 (#435)

- CHANGELOG.md
- library/src/level2/rocsparse_coomv.cpp
- library/src/level2/rocsparse_coomv_aos.cpp
- Cherrypicks in fix to coomv from master branch
- This fixes SWDEV-375413 occurring in rocALUTION
> Cherry-pick Fix coomv bug (#446)

- CHANGELOG.md
- library/src/level2/rocsparse_coomv.cpp
- library/src/level2/rocsparse_coomv_aos.cpp
> Revert "Fix coomv bug (#446) (#271)"

- clients/benchmarks/CMakeLists.txt
- clients/tests/CMakeLists.txt
- install.sh
Reverts ROCmSoftwarePlatform/rocSPARSE#264
> Revert "Remove RPATH/RUNPATH from ROCm libraries and binaries"

- CHANGELOG.md
- library/src/level2/rocsparse_coomv.cpp
- library/src/level2/rocsparse_coomv_aos.cpp
- Cherrypicks in fix to coomv from master branch
- This fixes SWDEV-375413 occurring in rocALUTION
> Fix coomv bug (#446)

- clients/tests/test_bsrsm.yaml
- clients/tests/test_csr2ell.yaml
- clients/tests/test_csrsm.yaml
- clients/tests/test_dotci.yaml
- clients/tests/test_doti.yaml
- clients/tests/test_spvv.yaml
- library/include/rocsparse-functions.h
- library/src/conversion/rocsparse_csr2ell.cpp
- library/src/level2/rocsparse_bsrsv_solve.cpp
- library/src/level2/rocsparse_csrsv_analysis.cpp
- library/src/level2/rocsparse_csrsv_solve.cpp
- library/src/level3/rocsparse_bsrsm_template_large.cpp
- library/src/level3/rocsparse_csrsm.cpp
- Fixes failures encountered when running hipgraph tests
- This involved removing some stream syncs for some routines and disabling hipgraph support for other routines until they can be fixed in 6.0 release
> Fix hipgraph failures

- library/src/level2/rocsparse_csrsv_analysis.cpp
- library/src/rocsparse_memstat.cpp
- scripts/rocsparse-memstat.py
Fixing memstat output json file and fixing a memory leak from trm_analysis
> Fixing memstat output json file and fixing a csrsv memory leak  (#507)

- CHANGELOG.md
- library/include/rocsparse-types.h
- library/src/precond/itilu0/rocsparse_csritilu0_buffer_size.cpp
- library/src/precond/itilu0/rocsparse_csritilu0_compute.cpp
- library/src/precond/itilu0/rocsparse_csritilu0_history.cpp
- library/src/precond/itilu0/rocsparse_csritilu0_preprocess.cpp
Temporarily disabling algorithm 4 of csritilu0
> Csritilu0 4 (#517)

- clients/benchmarks/CMakeLists.txt
- clients/benchmarks/rocsparse_bench_cmdlines.hpp
- clients/common/rocsparse_clients_envariables.cpp
- clients/common/rocsparse_importer_rocalution.cpp
- clients/common/rocsparse_importer_rocsparseio.cpp
- clients/common/rocsparse_matrix_factory.cpp
- clients/common/rocsparse_parse_data.cpp
- clients/include/rocsparse_clients_envariables.hpp
- clients/tests/CMakeLists.txt
Cherry pick matrix search path PR into 5.7
> Change rocsparse test/benchmark matrix search path (#494)

- clients/common/rocsparse_host.cpp
- clients/testings/testing_bsr2csr.cpp
- clients/testings/testing_prune_csr2csr.cpp
- clients/testings/testing_prune_csr2csr_by_percentage.cpp
- library/include/rocsparse-types.h
- library/src/conversion/rocsparse_coo2dense.cpp
- library/src/include/common.h
- library/src/precond/itilu0/rocsparse_csritilu0_buffer_size.cpp
- library/src/precond/itilu0/rocsparse_csritilu0_compute.cpp
- library/src/precond/itilu0/rocsparse_csritilu0_history.cpp
- library/src/precond/itilu0/rocsparse_csritilu0_preprocess.cpp
- library/src/precond/itilu0/rocsparse_csritilu0x_sync_fusion.cpp
- Cherrypick in fix for split fusion algorithm of csritilu0
> Fix xnack csritilu0 sync_split_fusion failures (#552)

- clients/testings/testing_csritilu0.cpp
- library/src/conversion/rocsparse_csxsldu_compute.cpp
- library/src/conversion/rocsparse_csxsldu_preprocess.cpp
- library/src/precond/itilu0/rocsparse_csritilu0_async_inplace.cpp
- Cherrypick f614256ee04c4aa85cceb1bc262b36c5310f570f into release-staging/rocm-rel-5.7
> Malloc (#497)

- library/src/conversion/rocsparse_csxsldu_preprocess.cpp
- library/src/precond/itilu0/rocsparse_csritilu0_async_inplace.cpp
- library/src/precond/itilu0/rocsparse_csritilu0_sync_split_fusion.cpp
- library/src/precond/itilu0/rocsparse_csritilu0x_driver.hpp
- library/src/precond/itilu0/rocsparse_csritilu0x_sync.cpp
- library/src/precond/itilu0/rocsparse_csritilu0x_sync_fusion.cpp
- Cherry-pick 71bfe6a868d519cdaafde2f34cc46b3b2b6e6d4e into release-staging/rocm-rel-5.7
> Fixing crashes with XNACK enabled (#499)

- clients/testings/testing_csritsv.cpp
- library/src/level2/rocsparse_csritsv_analysis.cpp
- library/src/level2/rocsparse_csritsv_solve.cpp
- Cherrypick in 75ab4005256f4473453810610f3c2cba7836a41b to release-staging/rocm-rel-5.7
> Csritsv xnack fix (#489)

- CHANGELOG.md
- CMakeLists.txt
> changelog 5.7

- library/src/extra/bsrgemm_device.h
- library/src/extra/csrgemm_device.h
- library/src/extra/rocsparse_csrgemm_numeric.cpp
- library/src/extra/rocsparse_csrgemm_symbolic.cpp
- library/src/include/common.h
- library/src/level2/bsrsv_device.h
- library/src/level2/coomv_device.h
- library/src/level2/csrmv_device.h
- library/src/level2/csrmv_symm_device.h
- library/src/level2/csrsv_device.h
- library/src/level2/ellmv_device.h
- library/src/level2/rocsparse_coomv.cpp
- library/src/level2/rocsparse_csritsv_analysis.cpp
- library/src/level2/rocsparse_csritsv_solve.cpp
- library/src/level3/bsrsm_device_large.h
- library/src/level3/csrmm_device.h
- library/src/level3/csrsm_device.h
- library/src/level3/rocsparse_coomm_template_atomic.cpp
- library/src/level3/rocsparse_coomm_template_segmented_atomic.cpp
- library/src/precond/bsric0_device.h
- library/src/precond/bsrilu0_device.h
- library/src/precond/csric0_device.h
- library/src/precond/csrilu0_device.h
- library/src/precond/itilu0/common.cpp
- library/src/precond/itilu0/rocsparse_csritilu0_async_inplace.cpp
- library/src/precond/itilu0/rocsparse_csritilu0x_async.cpp
- library/src/precond/itilu0/rocsparse_csritilu0x_sync.cpp
- library/src/precond/itilu0/rocsparse_csritilu0x_sync_fusion.cpp
- Cherrypicks in 80cf700ec27c6fb8e3f5ecc03e2a0d9726816e06 to resolved both SWDEV-418480 and SWDEV-408046
- Fixes failing compilation on windows
> Cherrypick SWDEV-408046 (#594)

- docs/doxygen/Doxyfile
- library/include/internal/conversion/rocsparse_gebsr2gebsr.h
- library/include/internal/conversion/rocsparse_prune_dense2csr.h
- library/include/internal/extra/rocsparse_bsrgeam.h
- library/include/internal/extra/rocsparse_bsrgemm.h
- library/include/internal/extra/rocsparse_csrgeam.h
- library/include/internal/extra/rocsparse_csrgemm.h
> chore: fix some typos
